### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by triangle959** [Thoosje/Incapsula-Generator#1]
[test link](https://www.wanhai.com/_Incapsula_Resource?SWUDNSAI=31&xinfo=7-87606006-0%200NNN%20RT%281648535512340%2065%29%20q%280%20-1%20-1%200%29%20r%280%20-1%29%20B12%288%2c881023%2c0%29%20U18&incident_id=256000590426328873-437056125460811463&edet=12&cinfo=08000000&rpinfo=0&cts=7lwM%2bwAWbcQ%2fpMQM2KUlhzFSzLiGSwVlHkbyAtK5fYQcGlbt0XqNl3Wy9Bb5zG5t&mth=GET)

**Comment by Thoosje** [comment]
This project was never finished, but I might continue working on it later.

**Comment by triangle959** [comment]
已收到

**Comment by Thoosje** [comment]
Hi, the code is very outdated. I made a working version. If needed please message me on discord: thoosje
